"""Reporter agent: Claude generates an HTML email digest, sent via SMTP."""

from ..llm import MODEL_DEFAULT, get_client
from ..models.listing import Listing
from ..tools.email_sender import send_html_email


def _format_listing_text(i: int, l: Listing, target_city: str) -> str:
    price_str = f"{l.price:,.0f} {l.currency or ''}".strip() if l.price else "N/A"
    loc = l.address or l.city or "N/A"
    if l.distance_km:
        loc += f" ({l.distance_km} km from {target_city})"
    return (
        f"### {i + 1}. {l.title or 'Property'}\n"
        f"- Price: {price_str}\n"
        f"- Location: {loc}\n"
        f"- Rooms: {l.rooms or 'N/A'} | Bedrooms: {l.bedrooms or 'N/A'} | Area: {l.area_sqm or 'N/A'} m²\n"
        f"- Type: {l.property_type or 'N/A'}\n"
        f"- Source: {l.source_website}\n"
        f"- URL: {l.url}\n"
        f"- Description: {l.description or 'N/A'}"
    )


def _generate_html(
    listings: list[Listing],
    target_city: str,
    search: dict,
) -> str:
    listings_md = "\n\n".join(
        _format_listing_text(i, l, target_city) for i, l in enumerate(listings)
    )

    prompt = f"""Generate a clean, professional HTML email body (NOT a full HTML document —
just the <body> content with inline CSS) for a home-search daily digest.

Search summary:
- Target: {target_city}, {search.get('target_country', '')}
- Radius: {search.get('perimeter_km')} km
- Budget: up to {search.get('price_max', 'N/A'):,}
- Min rooms: {search.get('min_rooms', 'N/A')}
- New listings found: {len(listings)}

Listings:
{listings_md}

Design requirements:
- Clean modern layout, blue/white colour scheme
- Summary banner at the top (count + search criteria)
- Each property as a card with all details and a clickable "View Listing" button
- Responsive (max-width: 700px)
- Footer: "Generated by HomeQuest AI · Powered by Gemini"

Return ONLY the HTML — no markdown fences, no explanation.
"""
    response = get_client().models.generate_content(
        model=MODEL_DEFAULT,
        contents=prompt,
    )
    return response.text.strip()


def send_report(
    listings: list[Listing],
    target_city: str,
    search: dict,
) -> None:
    if not listings:
        print("  No new listings — skipping email.")
        return

    print(f"  Generating HTML email for {len(listings)} listings …")
    html = _generate_html(listings, target_city, search)

    subject = f"HomeQuest: {len(listings)} new propert{'y' if len(listings) == 1 else 'ies'} near {target_city}"
    send_html_email(subject, html)
